import Head from "next/head";
import styles from "../styles/Home.module.css";
import Sidebar from "../components/Sidebar";
import Center from "../components/Center";
import Player from "../components/Player";
import {getSession} from 'next-auth/react'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Spotify 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black h-screen overflow-hidden flex">
        <Sidebar />
        <Center />
      </main>
      <div className="sticky bottom-0 left-0 z-50">
        <Player/>
      </div>
    </div>
  );
}

export async function getServerSideProps (context) {

  const session = await getSession(context)
  return {
    props: {
      session
    }
  }
}